### ISSUE TITLE
Analise do HTML feito em sala de aula.

### ISSUE THREAD

**Issue by MOVelasco** [simonGpinheiro/EstudoSalaDeAula#1]
Olá Simon.

Estou olhando primeiro arquivo que fizemos na nossa primeira aula de HTML, e o seu documento html, não está bem formatado e endentado, já que fizemos ele em Notepad++. Com o intuito de aprendermos a necessidade e utilidade de um código endentado. 
Algumas observações: As **TAGs** ``<head> e <body>`` não estão endentadas em relação a sua **TAG pai ``<html>``**.
Na **linha 10** do seu documento **HTML**  no estilo feito em linha, na TAG ``<h1>`` a instrução de ``margin:0;`` não esta entre " aspas. Por esse motivo, essa formatação não está funcionando.
OK?

**Comment by simonGpinheiro** [comment]
Boa noite 
As alterações foram feitas.
